title: NSF SBIR
theme: uswds-jekyll

url: https://seedfund.nsf.gov
baseurl: ""
permalink: pretty
deadline: June 14th, 2017

styles:
  - /assets/css/styles.css
sass:
  style: compressed

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

collections:
  apply:
    permalink: /how-to-apply/:path/
    output: true
  events:
    output: false
  timeline:
    output: false
  styleguide:
    output: true
    permalink: /styleguide/:path/

defaults:
  - scope:
      path: "_apply"
    values:
      layout: docs
  - scope:
      path: "_styleguide"
    values:
      layout: styleguide
      include_subnav: true

awards_api:
  date_start: '06/01/2016'
  date_end: '12/31/2016'
  active_date_start: '11/30/2016'
  update_to_current_time: false
  reset_date: false
