title: NSF SBIR
theme: jekyll-uswds

styles:
  - /assets/uswds/css/uswds.min.css

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

jekyll_get:
  - data: awards
    json: 'http://api.nsf.gov/services/v1/awards.json?agency=nsf'
