title: NSF SBIR Training
theme: jekyll-uswds

styles:
  - /assets/css/uswds-overrides.css


scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

jekyll_get:
  - data: awards
    json: 'http://api.nsf.gov/services/v1/awards.json?agency=nsf'
